---
driver:
  name: dokken
  chef_version: 14
  privileged: true

provisioner:
  name: dokken
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  nodes_path: 'test/fixtures/nodes'
  # chef_log_level: info

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: ubuntu-16
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]

  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[nsupdate]
    attributes:

