AllCops:
  TargetRubyVersion: 2.5
  DefaultFormatter: fuubar
  DisplayCopNames: true
  Exclude:
    - .berkshelf/**/*
    - Gemfile
    - Guardfile

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

RescueModifier:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
